### ISSUE TITLE
Проблема рендеринга нотации для редукции

### ISSUE THREAD

**Issue by gabriel-fallen** [suhr/tmath#3]
В [главе про функции](https://github.com/suhr/tmath/blob/master/prose/expr/fun.md) вводится нотация для редукции:
$${\color{red}e_1} \xrightarrow{\;*\;} {\color{red}e_2}$$
но далее по тексту она рендерится чаще всего без звёздочки, просто как `;;`.

Я бы предложил заменить на какую-нибудь нотацию попроще, которая рендерится всегда одинаково. Например, `;;` без звёздочки. 😉

PS. Браузер – Firefox @ Windows 11.

**Comment by suhr** [comment]
Здесь нотация рендерится нормально: https://suhr.github.io/tmath/expr/fun.html. А гитхаб, похоже, очень много чего там некорректно рендерит.

В сорце это `\xrightarrow{\;*\;}`, пара `\;` нужна чтобы получить длинную стрелку.

**Comment by gabriel-fallen** [comment]
Тогда вопрос снимается, извините за ложный вызов... 😅
