### ISSUE TITLE
Неоднозначная формулировка

### ISSUE THREAD

**Issue by gabriel-fallen** [suhr/tmath#5]
В [главе про синтаксис](https://suhr.github.io/tmath/expr/syn.html) говорится

> Кроме метапеременных бывают также и метавыражения — преобразования одного синтаксического дерева в другое. Мы их отдельно не выделяем.

Возникает неоднозначность: "отдельно не выделяем" – это про выделение цветом в тексте или в смысле "не выделяем при описании теории"?

**Comment by suhr** [comment]
В первую очередь цветом, но остальной текст также не делает сильных акцентов.

**Comment by gabriel-fallen** [comment]
Даже если обе интерпретации корректны, я бы предпочёл, чтобы это было написано явно, чем гадать "что хотел сказать автор"... 😅

**Comment by suhr** [comment]
Исправлено в последней версии.
